- name: Update and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: Install packages
  apt:
    name: ['git', 'python-psycopg2', 'postgresql', 'postgresql-contrib', 'libpq-dev', 'python3-pip', 'python3-dev',
           'nginx', 'curl', 'make', 'build-essential', 'libssl-dev', 'zlib1g-dev', 'libbz2-dev', 'libreadline-dev',
           'libsqlite3-dev', 'wget', 'llvm', 'libncurses5-dev', 'xz-utils', 'tk-dev', 'libxml2-dev', 'libxmlsec1-dev',
           'libffi-dev', ]
