- name: Clone pyenv git repo
  git: repo="https://github.com/pyenv/pyenv.git" dest="{{ pyenv_directory }}" force=yes
  become: True
  become_user: "{{ user }}"

- name: Install python 3.6.6
  shell: "{{ pyenv_directory }}/bin/pyenv install {{ python_version }}"
  become: True
  become_user: "{{ user }}"

- name: Clone pyenv-virtualenv git repo
  git: repo="https://github.com/pyenv/pyenv-virtualenv.git" dest="{{ pyenv_directory }}/plugins/pyenv-virtualenv" force=yes
  become: True
  become_user: "{{ user }}"

- name: Install virtual environment TS_env
  shell: "{{ pyenv_directory }}/bin/pyenv virtualenv {{ python_version }} {{ virtual_environment_name }}"
  become: True
  become_user: "{{ user }}"
