- name: Copy gunicorn.socket
  template:
    src: gunicorn.socket.j2
    dest: /etc/systemd/system/gunicorn.socket
    owner: root
    group: root

- name: Copy gunicorn.service
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    owner: root
    group: root

- name: Start and enable the Gunicorn socket
  systemd:
    name: gunicorn.socket
    state: started
    enabled: yes
